name: Publish testing
on: [ workflow_call ]

jobs:
  publish:
    if: github.repository == 'whyoleg/cryptography-kotlin'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
        with:
          cache-disabled: true

      - name: Publish to Maven Local
        run: ./gradlew publishToMavenLocal
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.signingKey}}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{secrets.signingPassword}}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{secrets.mavenCentralUsername}}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{secrets.mavenCentralPassword}}
